apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "instant-search-demo.fullname" . }}
  labels:
    {{- include "instant-search-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "instant-search-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "instant-search-demo.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "instant-search-demo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            {{- range $k,$v := .Values.env }}
            - name: {{ $k | quote }}
              value: {{ $v | quote}}
            {{- end }}
          livenessProbe:
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            httpGet:
              path: /
              port: http
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
            httpGet:
              path: /
              port: http

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
