{{- if .Values.privateRegistry.enabled }}
apiVersion: v1
data:
  .dockerconfigjson: "{{ printf "{\"auths\": {\"eu.gcr.io\": {\"auth\": \"%s\" } } }" (printf "oauth2accesstoken:%s" .Values.privateRegistry.password | b64enc)  | b64enc }}"
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "instant-search-demo.serviceAccountName" . }}-imagepullsecret
{{- end }}
