apiVersion: v1
kind: Service
metadata:
  name: {{ include "instant-search-demo.fullname" . }}
  labels:
    {{- include "instant-search-demo.labels" . | nindent 4 }}
  {{- if .Values.gcpBackendConfig }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    beta.cloud.google.com/backend-config: '{"ports": {"http":"{{ include "instant-search-demo.fullname" . }}"}}'
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  sessionAffinity: ClientIP
  selector:
    {{- include "instant-search-demo.selectorLabels" . | nindent 4 }}
