{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "instant-search-demo.serviceAccountName" . }}
  labels:
{{ include "instant-search-demo.labels" . | nindent 4 }}
{{- if .Values.privateRegistry.enabled }}
imagePullSecrets:
  - name: {{ include "instant-search-demo.serviceAccountName" . }}-imagepullsecret
{{- end }}
{{- end -}}
